version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      URL_MAESTRA: http://172.31.xx.xx:5000/farmacias
    volumes:
      - .:/app
    restart: unless-stopped
