version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      URL_MAESTRA: http://32.197.236.185/Farmacias_api.php
    volumes:
      - .:/app
    restart: unless-stopped
